CREATE TABLE player_stats (
	id INT primary key,
	player_name varchar(255) ,
    age INT,
    team varchar(255) ,
    position varchar(255) ,
    games INT,
    games_started INT,
    minutes INT,
    fg_made INT,
    fg_atp INT,
    fg_pct DECIMAL(5,2),
    three_made INT,
    three_atp INT,
    three_pct DECIMAL(5,2),
    two_made INT,
    two_atp INT,
    two_pct DECIMAL(5,2),
    efg_pct DECIMAL(5,2),
    ft_made INT,
    ft_atp INT,
    ft_pct DECIMAL(5,2),
    orb INT,
    drb INT,
    trb INT,
    ast INT,
    stl INT,
    blk INT,
    tov INT,
    pf INT,
    pts INT
);